# Assignment 1

Please enter your **name, surname** and **student number** instead of `"NAME-HERE"`, `"SURNAME-HERE"`, `"NUMBER-HERE"` below

In [1]:
student = {
    'name' : "Esra" ,
    'surname' : "Sekerci", 
    'studentNumber' : "2698215"
}

print(student)

{'name': 'Esra', 'surname': 'Sekerci', 'studentNumber': '2698215'}


This homework is composed of 3 parts with multiple questions. There is an empty or partially written code block under every question. Please complete those code blocks and run your code. 

## Part 1 (36 pts)

1. Create a random vector of size 5, $\pmb a \in \mathbb R^5$ (use the relevant `numpy` function for creating a random vector)

In [2]:
import numpy as np

In [3]:
a = np.random.rand(5)
a

array([0.72422595, 0.28085982, 0.58279845, 0.78210198, 0.10218111])

2. Create a vector of zeros of size 5, $\pmb b \in \mathbb R^5$ (use the relevant `numpy` function for creating a vector of zeros)

In [4]:
b = np.zeros(5)
b

array([0., 0., 0., 0., 0.])

3. Replace the fourth value of $\pmb b$ with $1$

In [5]:
b[3] = 1
b

array([0., 0., 0., 1., 0.])

4. Compute $\pmb a \cdot \pmb b$

In [6]:
np.dot(a, b)

0.782101975379373

In [7]:
a.dot(b)

0.782101975379373

5. Compute the norm of $\pmb a$

In [8]:
L1_a = np.linalg.norm(a, 1)
L1_a

2.4721673095964602

In [9]:
L2_a = np.linalg.norm(a, 2)
L2_a

1.2510651395010015

6. Create a $5 \times 5$ identity matrix $\pmb A \in \mathbb R^{5 \times 5}$

In [10]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. Replace the 1 values in $\pmb A$ by 3s

In [11]:
A[A == 1] = 3
A

array([[3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

8. Create a $2 \times 5$ matrix that is composed of Gaussian random samples $\pmb B \in \mathbb R^{2 \times 5}$ (check numpy documentation for a relevant function that creates gaussian samples)

In [12]:
B = np.random.normal(0, 1, size=(2, 5)) # with mean 0 and standard deviation 1
B

array([[ 0.03742873, -1.0552996 ,  1.26267016,  2.80430004, -0.95770349],
       [-0.76558436,  0.01040004,  1.81799602,  0.08745514,  1.57195947]])

In [13]:
from scipy.stats import shapiro

flatten_B = B.flatten()

shapiro(flatten_B)

ShapiroResult(statistic=0.9213145413822582, pvalue=0.3680493360216392)

9. Compute the matrix product $A B^T$

In [14]:
np.dot(A, B.T)

array([[ 0.11228618, -2.29675308],
       [-3.16589881,  0.03120011],
       [ 3.78801049,  5.45398807],
       [ 8.41290012,  0.26236541],
       [-2.87311046,  4.71587841]])

## Part 2 (24 pts)

1. Create a `numpy` array (vector) of 30 evenly spaced items between 2 and 20 using the relevant numpy method.

Output: `array([ 2.        ,  2.62068966,  3.24137931,  3.86206897,  4.48275862,
        5.10344828,  5.72413793,  6.34482759,  6.96551724,  7.5862069 ,
        8.20689655,  8.82758621,  9.44827586, 10.06896552, 10.68965517,
       11.31034483, 11.93103448, 12.55172414, 13.17241379, 13.79310345,
       14.4137931 , 15.03448276, 15.65517241, 16.27586207, 16.89655172,
       17.51724138, 18.13793103, 18.75862069, 19.37931034, 20.        ])`


In [15]:
np.linspace(2, 20, 30)

array([ 2.        ,  2.62068966,  3.24137931,  3.86206897,  4.48275862,
        5.10344828,  5.72413793,  6.34482759,  6.96551724,  7.5862069 ,
        8.20689655,  8.82758621,  9.44827586, 10.06896552, 10.68965517,
       11.31034483, 11.93103448, 12.55172414, 13.17241379, 13.79310345,
       14.4137931 , 15.03448276, 15.65517241, 16.27586207, 16.89655172,
       17.51724138, 18.13793103, 18.75862069, 19.37931034, 20.        ])

2. Let x be a `numpy` array `[[1, 2, 3], [4, 5, 6]]`. Convert it to `[1 4 2 5 3 6]`.

In [16]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.flatten(order='F')

array([1, 4, 2, 5, 3, 6])

3. Create a random `numpy` array $\pmb x$ of shape $3 \times 4$. Permute the dimensions of $\pmb x$ such that the new shape will be $4 \times 3$.

In [17]:
x = np.random.rand(3, 4)
x.shape

(3, 4)

In [18]:
x = x.reshape(4,3)

In [19]:
x.shape

(4, 3)

4. Create a random `numpy` array $\pmb x$ of shape $3 \times 4$. Permute the dimensions of $\pmb x$ such that the new shape will be $4 \times 1 \times 3$.

In [20]:
x = np.random.rand(3, 4)
x

array([[0.86212084, 0.91638435, 0.70165256, 0.86701058],
       [0.93259556, 0.13078605, 0.20120607, 0.53609563],
       [0.71359485, 0.37572608, 0.84319373, 0.9947905 ]])

In [21]:
x1 = np.expand_dims(x.T, axis=1)
x1.shape

(4, 1, 3)

In [22]:
x1

array([[[0.86212084, 0.93259556, 0.71359485]],

       [[0.91638435, 0.13078605, 0.37572608]],

       [[0.70165256, 0.20120607, 0.84319373]],

       [[0.86701058, 0.53609563, 0.9947905 ]]])

In [23]:
x2 = x.reshape((4, 1, 3))
x2.shape

(4, 1, 3)

In [24]:
x2

array([[[0.86212084, 0.91638435, 0.70165256]],

       [[0.86701058, 0.93259556, 0.13078605]],

       [[0.20120607, 0.53609563, 0.71359485]],

       [[0.37572608, 0.84319373, 0.9947905 ]]])

## Part 3 (40 pts)

1. Define the following $\mathbb R^{8 \times 2}$ matrix as a numpy 2-D array

$$\pmb X = \begin{bmatrix} 0 & 1 \\ 5 & 1 \\ 15 & 2 \\ 25 & 5 \\ 35 & 11 \\ 45 & 15 \\ 55 & 34 \\ 60 & 35 \end{bmatrix}$$

Consider this as a dataset of 2 features. Each row in this data is one observation of each feature.

In [25]:
X = np.array([
    [0, 1],
    [5, 1],
    [15, 2],
    [25, 5],
    [35, 11],
    [45, 15],
    [55, 34],
    [60, 35]
])

2. Define the following $\mathbb R^8$ vector as a 1-D numpy array

$$\pmb y = \begin{bmatrix}4 \\ 5 \\ 20 \\ 14 \\ 32 \\ 22 \\ 38 \\ 43 \end{bmatrix}$$

Consider this as a dataset of target values that you want to predict.

In [26]:
y = np.array([4, 5, 20, 14, 32, 22, 38, 43])

3. Compute the product

$$ \pmb X^T \pmb y$$

> Note:  check how to compute transpose of a matrix $\pmb X^T$ 
> Note: note that you are making matrix multiplication, not element-wise multiplication

In [27]:
np.dot(X.T, y)

array([7455, 3598])

4. Compute

$$(\pmb X^T \pmb X)^{-1}$$

> Note:  check how to compute inverse of a matrix in numpy

> Note: note that you are making matrix multiplication, not element-wise multiplication



In [28]:
XTX_inv = np.linalg.inv(np.dot(X.T, X))
XTX_inv

array([[ 0.00101681, -0.00191343],
       [-0.00191343,  0.00396328]])

5. Compute $$\beta = (\pmb X^T \pmb X)^{-1} \pmb X^T \pmb y$$

In [29]:
beta = np.dot(np.dot(XTX_inv, X.T), y)
beta

array([ 0.69579339, -0.00477437])


As a result you should get an 1-D array of 2 elements. If you find it, congratulations, you just applied your first machine learning algorithm, i.e. the least squares estimates for linear regression!

In [30]:
np.linalg.inv(X.T @ X) @ X.T @ y

array([ 0.69579339, -0.00477437])